### PR TITLE
supporting metamask login selection instead of login/password

### PR DESCRIPTION
**Pull request by yas51ne**
supporting metamask login selection instead of login/password introduced in bombcrypto version 33

### CODE REVIEW

**Comment by Bleujj1** [comment]
You need help?

**Comment by yas51ne** [comment]
The feature is working, i tested it on my environment, you can test it on your end and give me feedback if you want :)

**Comment by yas51ne** [comment]
Yes with 100% zoom

**Comment by cristianowelaski** [comment]
Não entendi... Sorry!

**Comment by cristianowelaski** [comment]
> You have to synchronize your wallet and then you debug it with the bech

My wallet is synchronized!

But he doesn't click on "Treasure Hunt" (identify_home)...

It already replaces the images. And python is up to date...

Please, help me!

**Comment by Bleujj1** [comment]
Then you have to debug it.. I can send you a verified secure bech ellipal
link. All you have to do is to folllow the step till you get to debug and
then you click on that

**Comment by thiagoc-machado** [comment]
same problem. stuck in tresure page

**Comment by renatofmmaia** [comment]
Thanks for your help @yas51ne!

We have already updated the bot to v4, which includes the new bomb login and some improvements that we identified in the process.

**Pull request closed without merging**
